package br.com.gestaonotavel.ifsul.model;

public enum Permission {
    VISUALIZAR_PACIENTES,
    CADASTRAR_PACIENTE,
    EDITAR_PACIENTE,
    EXCLUIR_PACIENTE,
    CRIAR_AGENDAMENTO,
    EDITAR_AGENDAMENTO,
    CANCELAR_AGENDAMENTO,
    REGISTRAR_VOLUNTARIADO,
    VER_VOLUNTARIADO,
    VER_FINANCEIRO,
    EDITAR_FINANCEIRO,
    GERAR_RELATORIOS,
    ADMINISTRAR_USUARIOS
}